import './components/tabs.js';
import './components/swipers.js';
import './components/video.js';
import './components/accordion.js';
import './components/transfer.js';
import './components/modals.js';
import './components/choices.js';
import './components/range.js';
import './components/form.js';